### ISSUE TITLE
Drugs are not harvestable

### ISSUE THREAD

**Issue by jxrxm** [lfuelling/esx_drugfarms#11]
I cloned the repo and its depedencies and it seems to work. But when entering a lab, there are no actions the player can do. Am I missing something or am I supposed to implement it myself?

**Comment by lfuelling** [comment]
Exactly, this mod does only provide the teleportation and map markers (see [this comment](https://github.com/lfuelling/esx_drugfarms/issues/10#issuecomment-670239102) for more info). I'll update the README to make this more clear.

If you manage to implement the functionality yourself I'd be really happy about a pull request or, if you decide to write your own mod providing the functionality, I'd be happy to link to it in the README.
